### ISSUE TITLE
Tests don't pass in ember 2.8.0-beta.1

### ISSUE THREAD

**Issue by mike-north** [networkteam/ember-cli-maskedinput#5]
From digging a little, seems like the synthesized keyboard events in a test or two aren't making it to the component. I'll do a git bisect to see what change to the framework introduced a problem

**Comment by mike-north** [comment]
This is a framework bug: https://github.com/emberjs/ember.js/issues/13888

**Comment by acorncom** [comment]
The bug above has been fixed, believe this issue can be closed

**Comment by hlubek** [comment]
Tested with Ember 2.8 and it worked for me
